module.exports = [
"[project]/.next-internal/server/app/[locale]/article/[uuid]/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/app/icon--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/icon--metadata.js [app-rsc] (ecmascript)"));
}),
"[project]/app/apple-icon--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/apple-icon--metadata.js [app-rsc] (ecmascript)"));
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/error.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/[locale]/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/[locale]/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/[locale]/error.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/[locale]/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/[locale]/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/components/feed/article/ArticleReader.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/feed/article/ArticleReader.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/feed/article/ArticleReader.tsx <module evaluation>", "default");
}),
"[project]/components/feed/article/ArticleReader.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/feed/article/ArticleReader.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/feed/article/ArticleReader.tsx", "default");
}),
"[project]/components/feed/article/ArticleReader.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$feed$2f$article$2f$ArticleReader$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/feed/article/ArticleReader.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$feed$2f$article$2f$ArticleReader$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/feed/article/ArticleReader.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$feed$2f$article$2f$ArticleReader$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/lib/feed-social.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "FALLBACK_THUMBNAIL_PATH",
    ()=>FALLBACK_THUMBNAIL_PATH,
    "SOCIAL_THUMBNAIL_SIZE",
    ()=>SOCIAL_THUMBNAIL_SIZE,
    "buildSocialDescription",
    ()=>buildSocialDescription,
    "buildSocialThumbnailUrl",
    ()=>buildSocialThumbnailUrl,
    "buildSocialTitle",
    ()=>buildSocialTitle,
    "loadFeedContent",
    ()=>loadFeedContent,
    "pickFeedImageSource",
    ()=>pickFeedImageSource,
    "stripHtml",
    ()=>stripHtml
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/app/config.ts [app-rsc] (ecmascript)");
;
;
const SOCIAL_THUMBNAIL_SIZE = 500;
const FALLBACK_THUMBNAIL_PATH = '/images/og-thumbnail.jpg';
const endpointByKind = {
    post: '/api/platform/community/feed/posts',
    article: '/api/platform/community/feed/articles'
};
const loadFeedContent = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (kind, identifier, locale)=>{
    try {
        const response = await fetch((0, __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getApiUrl"])(`${endpointByKind[kind]}/${encodeURIComponent(identifier)}`), {
            headers: {
                Accept: 'application/json',
                'Accept-language': locale
            },
            next: {
                revalidate: 300
            }
        });
        if (!response.ok) return null;
        const payload = await response.json();
        return payload.data ?? null;
    } catch  {
        return null;
    }
});
function pickFeedImageSource(item) {
    const image = item.media.find((media)=>media.media_type === 'image' && media.url);
    if (image?.url) return image.url;
    const thumbnail = item.media.find((media)=>media.thumbnail_url)?.thumbnail_url ?? item.media.find((media)=>media.media_type === 'thumbnail' && media.url)?.url;
    return thumbnail ?? null;
}
function buildSocialThumbnailUrl(kind, identifier) {
    return `${__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]}/social-image/${kind}/${encodeURIComponent(identifier)}`;
}
function stripHtml(html) {
    return html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
}
function buildSocialDescription(item, isArabic) {
    const source = stripHtml(item.body ?? item.excerpt ?? '');
    if (source) return source.slice(0, 160);
    const authorName = item.insighter?.name;
    if (!authorName) {
        return isArabic ? 'منشور على انسايتا.' : 'A post shared on Insighta.';
    }
    return isArabic ? `منشور بواسطة ${authorName} على انسايتا.` : `A post shared by ${authorName} on Insighta.`;
}
function buildSocialTitle(item, authorName, isArabic) {
    const explicitTitle = item.title?.trim();
    if (explicitTitle) return explicitTitle;
    const bodyTitle = stripHtml(item.body ?? item.excerpt ?? '').slice(0, 90).trim();
    if (bodyTitle) return bodyTitle;
    return isArabic ? `منشور بواسطة ${authorName}` : `A post by ${authorName}`;
}
}),
"[project]/app/[locale]/article/[uuid]/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ArticlePage,
    "generateMetadata",
    ()=>generateMetadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/app/config.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$feed$2f$article$2f$ArticleReader$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/feed/article/ArticleReader.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/feed-social.ts [app-rsc] (ecmascript)");
;
;
;
;
async function generateMetadata({ params }) {
    const { locale, uuid } = await params;
    const isArabic = locale === 'ar';
    const article = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["loadFeedContent"])('article', uuid, locale);
    if (!article) {
        return {
            title: isArabic ? 'ورقة بيضاء - انسايتا' : 'White Paper - Insighta Business',
            description: isArabic ? 'اقرأ ورقة بيضاء نشرها خبير في انسايتا.' : 'Read a White Paper published by an Insighta expert.'
        };
    }
    const authorName = article.insighter?.name ?? 'Insighta';
    const title = (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSocialTitle"])(article, authorName, isArabic);
    const description = (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSocialDescription"])(article, isArabic);
    const identifier = article.slug ?? article.uuid;
    const url = `${__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]}/${locale}/article/${identifier}`;
    const socialImage = (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSocialThumbnailUrl"])('article', identifier);
    return {
        metadataBase: new URL(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]),
        title,
        description,
        authors: [
            {
                name: authorName
            }
        ],
        creator: authorName,
        robots: {
            index: true,
            follow: true,
            googleBot: {
                index: true,
                follow: true,
                'max-image-preview': 'large'
            }
        },
        alternates: {
            canonical: url,
            languages: {
                en: `${__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]}/en/article/${identifier}`,
                ar: `${__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]}/ar/article/${identifier}`,
                'x-default': `${__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$config$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["publicBaseUrl"]}/en/article/${identifier}`
            }
        },
        openGraph: {
            type: 'article',
            locale: isArabic ? 'ar_SA' : 'en_US',
            url,
            siteName: 'Insighta',
            title,
            description,
            images: [
                {
                    url: socialImage,
                    width: __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SOCIAL_THUMBNAIL_SIZE"],
                    height: __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$feed$2d$social$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SOCIAL_THUMBNAIL_SIZE"],
                    type: 'image/jpeg',
                    alt: title
                }
            ],
            authors: [
                authorName
            ],
            ...article.published_at ? {
                publishedTime: article.published_at
            } : {}
        },
        twitter: {
            card: 'summary',
            site: '@INSIGHTA',
            title,
            description,
            images: [
                socialImage
            ]
        }
    };
}
async function ArticlePage({ params, searchParams }) {
    const { locale, uuid } = await params;
    const { source } = await searchParams;
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$feed$2f$article$2f$ArticleReader$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        locale: locale,
        identifier: uuid,
        isPublic: source !== 'my-feeds'
    }, void 0, false, {
        fileName: "[project]/app/[locale]/article/[uuid]/page.tsx",
        lineNumber: 92,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/[locale]/article/[uuid]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/[locale]/article/[uuid]/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__a4e04fbe._.js.map