// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[locale]/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reset-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signin">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signup">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/changelog">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/customers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/customers/single-post/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/customers/single-post">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/customers/single-post/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/insighter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/insighter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/Filter-knowledges/[taxonomy]/[id]/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/Filter-knowledges/[taxonomy]/[id]/[type]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/Filter-knowledges/[taxonomy]/[id]/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/all-industries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/all-industries">> = Specific
  const handler = {} as typeof import("../../app/[locale]/all-industries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/callback/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/callback/[token]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/callback/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/callback">> = Specific
  const handler = {} as typeof import("../../app/[locale]/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout">> = Specific
  const handler = {} as typeof import("../../app/[locale]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/contact-messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/contact-messages">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/contact-messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/consulting-fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/consulting-fields">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/consulting-fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/guidelines/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/guidelines/[type]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/guidelines/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/guidelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/guidelines">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/guidelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/hs-codes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/hs-codes">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/hs-codes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/isic-codes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/isic-codes">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/isic-codes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/tags">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/content/topics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/content/topics">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/content/topics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/admin-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/admin-sales">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/admin-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/insighters-wallets/[id]/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/insighters-wallets/[id]/transactions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/insighters-wallets/[id]/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/insighters-wallets/[id]/transfer-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/insighters-wallets/[id]/transfer-form">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/insighters-wallets/[id]/transfer-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/insighters-wallets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/insighters-wallets">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/insighters-wallets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/orders">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/finance/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/transactions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/finance/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/geography/countries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/geography/countries">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/geography/countries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/geography/economic-block/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/geography/economic-block">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/geography/economic-block/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/geography/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/geography">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/geography/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/geography/regions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/geography/regions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/geography/regions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/requests">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users/clients">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users/companies">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/insighters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users/insighters">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/insighters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/roles-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users/roles-permissions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/roles-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/users/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/users/staff">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/users/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/guest-download/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/guest-download">> = Specific
  const handler = {} as typeof import("../../app/[locale]/guest-download/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/home">> = Specific
  const handler = {} as typeof import("../../app/[locale]/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/industries/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/industries/[type]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/industries/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/industry-by-type/[type]/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/industry-by-type/[type]/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/industry-by-type/[type]/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/industry/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/industry/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/industry/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/account-settings/consulting-schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/account-settings/consulting-schedule">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/account-settings/consulting-schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/account-settings/general-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/account-settings/general-settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/account-settings/general-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/account-settings/notification-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/account-settings/notification-settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/account-settings/notification-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/account-settings/payment-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/account-settings/payment-settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/account-settings/payment-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/account-settings/project-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/account-settings/project-settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/account-settings/project-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-company-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-company-settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-company-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-consulting-schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-consulting-schedule">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-consulting-schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-downloads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-downloads">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-downloads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge/general">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge/packages">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/posted/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge/posted">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/posted/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/scheduled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge/scheduled">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/scheduled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/unpublished/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-knowledge/unpublished">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/unpublished/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-meetings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-orders">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/my-requests">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/on-work-projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/on-work-projects">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/on-work-projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/project-offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/project-offers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/project-offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/projects-created/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/projects-created">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/projects-created/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/read-later/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/read-later">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/read-later/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/sales">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/insighter-dashboard/wallet">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/knowledge/[type]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/knowledge/[type]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/knowledge/[type]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/knowledges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/knowledges">> = Specific
  const handler = {} as typeof import("../../app/[locale]/knowledges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/legals/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legals/cookies">> = Specific
  const handler = {} as typeof import("../../app/[locale]/legals/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/legals/licensing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legals/licensing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/legals/licensing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/legals/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legals/privacy">> = Specific
  const handler = {} as typeof import("../../app/[locale]/legals/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/legals/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legals/terms">> = Specific
  const handler = {} as typeof import("../../app/[locale]/legals/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/package/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/package/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/package/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/payment/stripe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/payment/stripe">> = Specific
  const handler = {} as typeof import("../../app/[locale]/payment/stripe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/[uuid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile/[uuid]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/[uuid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/settings/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile/settings/certificates">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/settings/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/settings/company/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile/settings/company/certificates">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/settings/company/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile/settings/company">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile/settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/project">> = Specific
  const handler = {} as typeof import("../../app/[locale]/project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/project/wizard/[step]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/project/wizard/[step]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/project/wizard/[step]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/faqs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/insightas-transparent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/client-account/insightas-transparent">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/insightas-transparent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/pillars-of-trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/client-account/pillars-of-trust">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/pillars-of-trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/value-proposition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/client-account/value-proposition">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/value-proposition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/what-you-can-do/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/client-account/what-you-can-do">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/what-you-can-do/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/why-insighta-is/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/client-account/why-insighta-is">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/client-account/why-insighta-is/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/company-accounts/why-a-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/company-accounts/why-a-company">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/company-accounts/why-a-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/how-do-clients-reach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/how-do-clients-reach">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/how-do-clients-reach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/who-can-become-an-insighter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/who-can-become-an-insighter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/who-can-become-an-insighter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/your-digital-knowledge-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/your-digital-knowledge-base">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/account-types/insighter-account/your-digital-knowledge-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/content-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/content-types">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/content-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/after-publishing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/after-publishing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/after-publishing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/golden-tips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/golden-tips">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/golden-tips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/online-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/online-consulting">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/online-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/publishing-and-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/publishing-and-content">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/publishing-and-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/real-value/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/real-value">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/real-value/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/for-experts/strategies-to-increase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/for-experts/strategies-to-increase">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/for-experts/strategies-to-increase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/getting-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/getting-started">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/getting-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/what-is-insighta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/what-is-insighta">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/what-is-insighta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/why-insighta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/about-insighta/why-insighta">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/why-insighta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/becoming-an-insighter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/becoming-an-insighter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/becoming-an-insighter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/booking-consulting-sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/booking-consulting-sessions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/booking-consulting-sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/buying-insights-and-multi-file-documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/buying-insights-and-multi-file-documents">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/buying-insights-and-multi-file-documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/checkout-and-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/checkout-and-payment">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/checkout-and-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/client-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/client-dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/client-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/faq">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/registration-account-basics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/registration-account-basics">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/registration-account-basics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/search-results-and-insight-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/search-results-and-insight-page">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/search-results-and-insight-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/searching-for-insights-and-experts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/searching-for-insights-and-experts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/searching-for-insights-and-experts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/support">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/what-is-insighta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/client-guide/what-is-insighta">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/what-is-insighta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/ai-summaries-and-metadata/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/ai-summaries-and-metadata">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/ai-summaries-and-metadata/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/becoming-an-insighter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/becoming-an-insighter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/becoming-an-insighter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/best-practices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/best-practices">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/best-practices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/company-accounts-and-team-activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/company-accounts-and-team-activity">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/company-accounts-and-team-activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/consulting-sessions-and-meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/consulting-sessions-and-meetings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/consulting-sessions-and-meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/insighter-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/insighter-dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/insighter-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/pricing-and-file-strategy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/pricing-and-file-strategy">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/pricing-and-file-strategy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/publishing-insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/publishing-insights">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/publishing-insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/responding-to-client-questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/responding-to-client-questions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/responding-to-client-questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/sales-earnings-and-wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/sales-earnings-and-wallet">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/sales-earnings-and-wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/support-and-troubleshooting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/support-and-troubleshooting">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/support-and-troubleshooting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/what-is-an-insighter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/first-steps/insighter-guide/what-is-an-insighter">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/what-is-an-insighter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/help-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/help-center">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/help-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/user-guide/getting-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/user-guide/getting-started">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/user-guide/getting-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/user-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/resources/user-guide">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/user-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/signout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signout">> = Specific
  const handler = {} as typeof import("../../app/[locale]/signout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/sub-industry-by-type/[type]/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sub-industry-by-type/[type]/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/sub-industry-by-type/[type]/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/sub-industry/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sub-industry/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/sub-industry/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/topic-by-type/[type]/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/topic-by-type/[type]/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/topic-by-type/[type]/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/topic/[id]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/topic/[id]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/topic/[id]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/update-country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/update-country">> = Specific
  const handler = {} as typeof import("../../app/[locale]/update-country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/api/hello/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/api/hello">> = Specific
  const handler = {} as typeof import("../../app/[locale]/api/hello/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[locale]/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(default)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(default)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/callback/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/callback">> = Specific
  const handler = {} as typeof import("../../app/[locale]/callback/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/geography/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/geography">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/geography/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/insighter-dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/insighter-dashboard/my-knowledge/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/insighter-dashboard/my-knowledge">> = Specific
  const handler = {} as typeof import("../../app/[locale]/insighter-dashboard/my-knowledge/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/profile/[uuid]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/profile/[uuid]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/profile/[uuid]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/about-insighta/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/resources/first-steps/about-insighta">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/about-insighta/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/client-guide/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/resources/first-steps/client-guide">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/client-guide/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/resources/first-steps/insighter-guide/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/resources/first-steps/insighter-guide">> = Specific
  const handler = {} as typeof import("../../app/[locale]/resources/first-steps/insighter-guide/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
